### ISSUE TITLE
There is a requirement that requires me to add a link into the message on error

### ISSUE THREAD

**Issue by ducqhl** [edwardfxiao/react-inputs-validation#29]
**There is a requirement that requires me to add a link into the message on error**
When the user types data into the textbox input, base on a condition I need to show an error message that contains a link.

**Solution**
It would be greate if MessageOnError and CustomFunc support React Component

**Comment by edwardfhsiao** [comment]
@kitokip Check v4.7.0 out, which provides ```shouldRenderMsgAsHtml``` in the ```validationOption``` to furfil your need.

Search ```asyncMsgObj.shouldRenderMsgAsHtml``` in the doc https://github.com/edwardfhsiao/react-inputs-validation/blob/master/docs/v4-doc.md#Textbox

**Comment by kitokip** [comment]
Look like that it doesn't affect for `customFunc` function?

**Comment by edwardfhsiao** [comment]
https://codesandbox.io/s/custom-functionwhen-providing-customfunc-forked-szsy4?file=/src/index.js

look at sencond textbox

**Comment by edwardfhsiao** [comment]
@kitokip sorry, it's my mistake, it should be ```validationOption. shouldRenderMsgAsHtml```

**Comment by edwardfhsiao** [comment]
I am closing this for now, feel free to reopen if you have further issues.
